### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by codeallthethingz**

### CODE REVIEW

**Comment by codeallthethingz** [comment]
@bvanvugt How does this look as a placeholder.

**Comment by bvanvugt** [comment]
Looks great, just two suggestions:
- add something about writing a good PR description to the last list
- how do you feel about linking to the roadmap, suggesting that a) contributors can find things we want to do listed there, and b) contributors can propose ideas for discussion prior to writing code?

**Comment by codeallthethingz** [comment]
@bvanvugt added a section at the top for those two points.

**Comment by codeallthethingz** [comment]
closes https://github.com/battlesnakeio/roadmap/issues/8

**Pull request merged**
